import { useEffect, useState } from "react";
import { getAlbum } from "../../api/albums";
import { getLegacyRating, previewLegacyReconciliation, reconcileLegacyRating } from "../../api/legacy";
import type { Album, LegacyRatingDetail } from "../../api/types";

export function LegacyReconciliationPage({ albumId, onBack }: { albumId: number; onBack: () => void }) {
  const [album, setAlbum] = useState<Album | null>(null); const [legacy, setLegacy] = useState<LegacyRatingDetail | null>(null); const [titles, setTitles] = useState<string[]>([]); const [mappings, setMappings] = useState<string[]>([]); const [preview, setPreview] = useState<{ pre_rating: number | null; bad_experience: number | null; final_rating: number | null } | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(true); const [done, setDone] = useState<string | null>(null);
  useEffect(() => { getAlbum(albumId).then(async (loaded) => { setAlbum(loaded); setTitles(loaded.tracks.map((track) => track.title)); if (!loaded.latest_legacy_rating) throw new Error("No legacy rating is available."); const detail = await getLegacyRating(loaded.latest_legacy_rating.id); setLegacy(detail); setMappings(detail.extracted_scores.map(() => "")); }).catch((e: Error) => setError(e.message)).finally(() => setBusy(false)); }, [albumId]);
  const tracks = album?.tracks.length ? album.tracks : titles.map((title, index) => ({ id: index + 1, position: index + 1, title })); const mapped = mappings.filter(Boolean).length; const valid = legacy && mapped === legacy.extracted_scores.length && new Set(mappings).size === mappings.length && tracks.length > 0;
  const payload = () => mappings.map((trackId, index) => ({ legacy_score_index: index, track_id: Number(trackId) }));
  const trackTitles = () => album?.tracks.length ? [] : titles;
  async function calculatePreview() { if (!legacy || !valid) return; setBusy(true); setError(null); try { setPreview(await previewLegacyReconciliation(legacy.id, trackTitles(), payload())); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function confirm() { if (!legacy || !valid) return; setBusy(true); try { const result = await reconcileLegacyRating(legacy.id, trackTitles(), payload()); setDone(`Reconciled as revision #${result.revision_id}.`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (busy && !album) return <main className="page"><p>Loading reconciliation…</p></main>; if (error && !album) return <main className="page"><button className="back" onClick={onBack}>← Album</button><p className="notice error">{error}</p></main>;
  return <main className="page narrow"><button className="back" onClick={onBack}>← Album</button><p className="eyebrow">Legacy reconciliation</p><h1>{album?.title}</h1>{error && <p className="notice error">{error}</p>}{done && <p className="notice success">{done}</p>}<section className="form-section"><h2>1. Real tracklist</h2>{album && !album.tracks.length && <><textarea rows={5} value={titles.join("\n")} onChange={(e) => { setTitles(e.target.value.split(/\r?\n/).filter(Boolean)); setPreview(null); }} placeholder="One track per line" /><p>Tracks will be created only when reconciliation is confirmed.</p></>}{album?.tracks.length ? <p>Using the existing real tracklist.</p> : null}</section><section className="form-section"><h2>2. Map legacy scores manually</h2><p>Assigned {mapped} / {legacy?.extracted_scores.length ?? 0} · Unrated tracks: {Math.max(0, tracks.length - mapped)}</p>{legacy?.extracted_scores.map((score, index) => <label key={index}>Legacy score {index + 1} — {score}<select value={mappings[index] ?? ""} onChange={(e) => { setMappings((current) => current.map((value, i) => i === index ? e.target.value : value)); setPreview(null); }}><option value="">Choose a real track</option>{tracks.map((track) => <option key={track.id} value={track.id}>{track.position}. {track.title}</option>)}</select></label>)}</section><section className="form-section"><h2>3. Preview and confirm</h2><p>All legacy scores must be assigned once. Unmapped real tracks remain explicitly unrated, not scored zero.</p><button onClick={calculatePreview} disabled={!valid || busy || !!done}>Calculate authoritative preview</button>{preview && <p>Reconstructed: pre {preview.pre_rating ?? "—"}, bad experience {preview.bad_experience ?? "—"}, final {preview.final_rating ?? "—"}. Legacy final: {legacy?.legacy_final_rating ?? "—"}.</p>}<button onClick={confirm} disabled={!valid || busy || !!done}>{busy ? "Reconciling…" : "Create native revision"}</button></section></main>;
}
