import { useEffect, useMemo, useState } from "react";
import { getAlbum } from "../../api/albums";
import { listRevisions, createRevision, getRevision } from "../../api/revisions";
import type { Album, RatingRevisionDetail, RatingRevisionSummary, TrackRatingRevisionCreate } from "../../api/types";
import { ratingPreviewCalculator } from "./ratingPreviewCalculator";
import { RatingHistory } from "./RatingHistory";
import { RevisionDetailPage } from "./RevisionDetailPage";
import { emptyRatingDraft, revisionToRatingDraft, type DraftTrack, type RatingDraft } from "./ratingDraft";
import { formatRevisionDate } from "./RatingHistory";
import { AlbumCover } from "../albums/AlbumCover";
import { CoverControls } from "../albums/CoverControls";

const fmt = (value: number | null, digits = 3) => value === null ? "—" : value.toFixed(digits);
const valueInRange = (value: string) => { const number = Number(value); return value !== "" && Number.isFinite(number) && number >= 0 && number <= 10; };
export function RatingEditorPage({ albumId, onBack, onReconcile }: { albumId: number; onBack: () => void; onReconcile: () => void }) {
  const [album, setAlbum] = useState<Album | null>(null); const [tracks, setTracks] = useState<DraftTrack[]>([]); const [coherence, setCoherence] = useState("5"); const [emotion, setEmotion] = useState("5"); const [coherenceNotes, setCoherenceNotes] = useState(""); const [emotionNotes, setEmotionNotes] = useState(""); const [albumNotes, setAlbumNotes] = useState(""); const [revisions, setRevisions] = useState<RatingRevisionSummary[]>([]); const [selectedRevisionId, setSelectedRevisionId] = useState<number | null>(null); const [selectedRevision, setSelectedRevision] = useState<RatingRevisionDetail | null>(null); const [draftSourceDate, setDraftSourceDate] = useState<string | null>(null); const [draftWarning, setDraftWarning] = useState<string | null>(null); const [rateAgainLoading, setRateAgainLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [revisionLoading, setRevisionLoading] = useState(false); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState<RatingRevisionDetail | null>(null);
  const refreshHistory = () => listRevisions(albumId).then(setRevisions);
  const applyDraft = (draft: RatingDraft) => { setTracks(draft.tracks); setCoherence(draft.coherence); setCoherenceNotes(draft.coherenceNotes); setEmotion(draft.emotion); setEmotionNotes(draft.emotionNotes); setAlbumNotes(draft.albumNotes); };
  useEffect(() => { Promise.all([getAlbum(albumId), refreshHistory()]).then(([loadedAlbum]) => { setAlbum(loadedAlbum); applyDraft(emptyRatingDraft(loadedAlbum)); }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)); }, [albumId]);
  useEffect(() => { if (selectedRevisionId === null) { setSelectedRevision(null); return; } let active = true; setSelectedRevision(null); setRevisionLoading(true); setError(null); getRevision(albumId, selectedRevisionId).then((revision) => { if (active) setSelectedRevision(revision); }).catch((e: Error) => { if (active) setError(e.message); }).finally(() => { if (active) setRevisionLoading(false); }); return () => { active = false; }; }, [albumId, selectedRevisionId]);
  const scoresValid = tracks.every((track) => valueInRange(track.score)); const subjectiveValid = valueInRange(coherence) && valueInRange(emotion);
  const preview = useMemo(() => scoresValid && subjectiveValid ? ratingPreviewCalculator(tracks.map((track) => ({ score: Number(track.score), includeInPreRating: track.include })), Number(coherence), Number(emotion)) : null, [tracks, coherence, emotion, scoresValid, subjectiveValid]);
  const changeTrack = (index: number, change: Partial<DraftTrack>) => setTracks((current) => current.map((track, i) => i === index ? { ...track, ...change } : track));
  async function save() { setError(null); if (!scoresValid || !subjectiveValid) { setError("Give every score, coherence, and emotion a value from 0 to 10 before saving."); return; } const payload = { coherence: Number(coherence), coherence_notes: coherenceNotes || null, emotion: Number(emotion), emotion_notes: emotionNotes || null, album_notes: albumNotes || null, tracks: tracks.map<TrackRatingRevisionCreate>((track) => ({ track_id: track.trackId, score: Number(track.score), include_in_pre_rating: track.include, notes: track.notes || null })) }; setSaving(true); try { const revision = await createRevision(albumId, payload); setSaved(revision); setDraftSourceDate(null); setDraftWarning(null); await refreshHistory(); } catch (e) { setError((e as Error).message); } finally { setSaving(false); } }
  if (loading) return <main className="page"><p>Loading album…</p></main>; if (error && !album) return <main className="page"><button className="back" onClick={onBack}>← Albums</button><p className="notice error" role="alert">{error}</p></main>; if (!album) return null;
  if (selectedRevisionId !== null) { if (revisionLoading) return <main className="page"><button className="back" onClick={() => setSelectedRevisionId(null)}>← Back to current rating</button><p>Loading revision…</p></main>; if (selectedRevision) return <RevisionDetailPage album={album} revision={selectedRevision} onBack={() => setSelectedRevisionId(null)} />; return <main className="page"><button className="back" onClick={() => setSelectedRevisionId(null)}>← Back to current rating</button><p className="notice error" role="alert">{error || "This revision could not be loaded."}</p></main>; }
  const summary = saved ? { preRating: saved.pre_rating, badExperience: saved.bad_experience, finalRating: saved.final_rating } : preview;
  const latestRevision = [...revisions].sort((left, right) => new Date(right.created_at).getTime() - new Date(left.created_at).getTime() || right.id - left.id)[0];
  async function rateAgain() { if (!latestRevision || !album) return; const currentAlbum = album; setRateAgainLoading(true); setError(null); try { const revision = await getRevision(albumId, latestRevision.id); const { draft, ignoredSnapshotTrackIds } = revisionToRatingDraft(currentAlbum, revision); applyDraft(draft); setSaved(null); setDraftSourceDate(revision.created_at); setDraftWarning(ignoredSnapshotTrackIds.length ? `${ignoredSnapshotTrackIds.length} removed historical track${ignoredSnapshotTrackIds.length === 1 ? " was" : "s were"} not included in this draft.` : null); } catch (e) { setError((e as Error).message); } finally { setRateAgainLoading(false); } }
  function startFresh() { if (!album) return; applyDraft(emptyRatingDraft(album)); setDraftSourceDate(null); setDraftWarning(null); setSaved(null); }
  return <main className="page editor"><button className="back" onClick={onBack}>← Back to album</button><header className="album-header"><div className="album-header-main"><AlbumCover album={album} className="editor-cover" /><div><p className="eyebrow">Listening session</p><h1>{album.title}</h1><p>{album.artist} · {album.year ?? "Year unknown"} · {album.release_type}{` · Previous ratings: ${revisions.length}`}</p><CoverControls album={album} onUpdated={setAlbum} /></div></div></header>
    {album.latest_legacy_rating?.reconciliation_status === "pending" && <p className="notice warning">Legacy rating imported. <button className="text-button" onClick={onReconcile}>Reconcile legacy rating</button></p>}{saved && <p className="notice success" role="status">Rating saved as revision #{saved.id}. These are the server-calculated values.</p>}{error && <p className="notice error" role="alert">{error}</p>}{draftWarning && <p className="notice warning" role="status">{draftWarning}</p>}
    {latestRevision && <section className="rate-again"><div><p className="eyebrow">Latest rating</p><p>{formatRevisionDate(latestRevision.created_at)} · {latestRevision.final_rating === null ? "—" : latestRevision.final_rating.toFixed(3)}</p></div><button onClick={rateAgain} disabled={rateAgainLoading}>{rateAgainLoading ? "Loading latest rating…" : "Rate again from latest"}</button></section>}
    {draftSourceDate && <p className="draft-source" role="status">Draft based on {formatRevisionDate(draftSourceDate)} rating. Saving creates a new revision. <button className="text-button" onClick={startFresh}>Start fresh</button></p>}
    <div className="editor-layout"><section><h2>Tracks</h2>{tracks.map((track, index) => <article className="rating-track" key={track.trackId}><h3><span>{String(track.position).padStart(2, "0")}</span>{track.title}</h3><div className="rating-controls"><label>Rating<input type="number" min="0" max="10" step="0.1" value={track.score} onChange={(e) => { setSaved(null); changeTrack(index, { score: e.target.value }); }} aria-invalid={track.score !== "" && !valueInRange(track.score)} /></label><label className="checkbox"><input type="checkbox" checked={track.include} onChange={(e) => { setSaved(null); changeTrack(index, { include: e.target.checked }); }} /> Include in PRE</label></div><label>Notes<textarea rows={3} value={track.notes} onChange={(e) => changeTrack(index, { notes: e.target.value })} placeholder="What stands out?" /></label></article>)}</section>
      <aside className="summary"><h2>Rating summary</h2><dl><div><dt>PRE</dt><dd>{fmt(summary?.preRating ?? null, 3)}</dd></div><div><dt>Coherence</dt><dd>{fmt(valueInRange(coherence) ? Number(coherence) : null, 1)}</dd></div><div><dt>Bad experience</dt><dd>{summary ? `${fmt(summary.badExperience, 2)} %` : "—"}</dd></div><div><dt>Emotion</dt><dd>{fmt(valueInRange(emotion) ? Number(emotion) : null, 1)}</dd></div><div className="final"><dt>Final rating</dt><dd>{fmt(summary?.finalRating ?? null, 3)}</dd></div></dl>{!preview && !saved && <p className="summary-note">Include at least one track and enter valid scores to calculate the rating.</p>}</aside>
    </div><section className="album-assessment"><h2>Album assessment</h2><div className="assessment-grid"><label>Coherence (0–10)<input type="number" min="0" max="10" step="0.1" value={coherence} onChange={(e) => { setSaved(null); setCoherence(e.target.value); }} /></label><label>Emotion (0–10)<input type="number" min="0" max="10" step="0.1" value={emotion} onChange={(e) => { setSaved(null); setEmotion(e.target.value); }} /></label></div><label>Coherence notes<textarea rows={4} value={coherenceNotes} onChange={(e) => setCoherenceNotes(e.target.value)} /></label><label>Emotion notes<textarea rows={4} value={emotionNotes} onChange={(e) => setEmotionNotes(e.target.value)} /></label><label>Album notes<textarea className="long-notes" rows={8} value={albumNotes} onChange={(e) => setAlbumNotes(e.target.value)} placeholder="Write freely about the album…" /></label><button onClick={save} disabled={saving || !tracks.length}>{saving ? "Saving…" : "Save rating"}</button></section><RatingHistory revisions={revisions} onSelect={setSelectedRevisionId} />
  </main>;
}
