import { useState } from "react";
import { commitLegacyImport, previewLegacyImport } from "../../api/imports";
import type { LegacyImportPreview } from "../../api/types";

export function LegacyImportPage({ onBack }: { onBack: () => void }) {
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<LegacyImportPreview | null>(null); const [selected, setSelected] = useState<Set<number>>(new Set()); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<string | null>(null);
  async function inspect() { if (!file) return; setBusy(true); setError(null); try { const next = await previewLegacyImport(file); setPreview(next); setSelected(new Set(next.rows.filter((row) => row.status === "ready" || row.status === "unrated").map((row) => row.row_number))); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function commit() { if (!file) return; setBusy(true); setError(null); try { const summary = await commitLegacyImport(file, [...selected]); setResult(`Imported ${summary.imported} · Skipped ${summary.skipped} · Failed ${summary.failed}`); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  const counts = preview?.rows.reduce((total, row) => ({ ...total, [row.status]: total[row.status] + 1 }), { ready: 0, unrated: 0, warning: 0, error: 0 }) ?? { ready: 0, unrated: 0, warning: 0, error: 0 };
  return <main className="page"><button className="back" onClick={onBack}>← Library</button><p className="eyebrow">Legacy migration</p><h1>Import legacy ratings</h1><p>Scores extracted from PRE formulas remain legacy metadata until you reconcile a real tracklist.</p><label className="import-file">Excel workbook (.xlsx)<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setPreview(null); setResult(null); }} /></label><button onClick={inspect} disabled={!file || busy}>{busy ? "Reading workbook…" : "Preview import"}</button>{error && <p className="notice error" role="alert">{error}</p>}{result && <p className="notice success" role="status">{result}</p>}{preview && <section className="import-preview"><p><strong>{preview.rows.length}</strong> rows · {counts.ready} ready · {counts.unrated} unrated · {counts.warning} warnings · {counts.error} errors</p><ol>{preview.rows.map((row) => <li key={row.row_number}><label><input type="checkbox" checked={selected.has(row.row_number)} disabled={row.status === "error"} onChange={() => { setSelected((current) => { const next = new Set(current); next.has(row.row_number) ? next.delete(row.row_number) : next.add(row.row_number); return next; }); }} /><strong>{row.title ?? "Untitled"}</strong> · {row.artist ?? "Unknown artist"} · {row.status === "unrated" ? "Not rated" : `computed ${row.computed_final_rating ?? "—"}`} <em>{row.status}</em></label><details><summary>Audit details</summary><p>Formula: {row.pre_formula ?? "—"} · {row.extracted_score_count} extracted scores</p><p>Legacy PRE: {row.legacy_pre_rating ?? "—"} · Computed PRE: {row.computed_pre_rating ?? "—"} · Legacy bad experience: {row.legacy_bad_experience ?? "—"} · Computed bad experience: {row.computed_bad_experience ?? "—"}</p>{[...row.warnings, ...row.errors].map((message) => <p key={message}>{message}</p>)}</details></li>)}</ol><button onClick={commit} disabled={busy || !selected.size}>{busy ? "Importing…" : "Import selected rows"}</button></section>}</main>;
}
