import { type FormEvent, useEffect, useState } from "react";
import { getArtist, updateArtist } from "../../api/artists";
import type { ArtistDetail, ArtistType } from "../../api/types";
import { ArtistImage } from "./ArtistImage";
import { ArtistImageControls } from "./ArtistImageControls";

export function EditArtistPage({ artistId, onCancel, onSaved }: { artistId: number; onCancel: () => void; onSaved: () => void }) {
  const [artist, setArtist] = useState<ArtistDetail | null>(null); const [name, setName] = useState(""); const [type, setType] = useState<ArtistType>("unknown"); const [countryCode, setCountryCode] = useState(""); const [birthDate, setBirthDate] = useState(""); const [deathDate, setDeathDate] = useState(""); const [formedYear, setFormedYear] = useState(""); const [dissolvedYear, setDissolvedYear] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { getArtist(artistId).then((loaded) => { setArtist(loaded); setName(loaded.name); setType(loaded.artist_type ?? "unknown"); setCountryCode(loaded.country_code ?? ""); setBirthDate(loaded.birth_date ?? ""); setDeathDate(loaded.death_date ?? ""); setFormedYear(loaded.formed_year?.toString() ?? ""); setDissolvedYear(loaded.dissolved_year?.toString() ?? ""); }).catch((cause: Error) => setError(cause.message)); }, [artistId]);
  const dirty = artist !== null && (name !== artist.name || type !== (artist.artist_type ?? "unknown") || countryCode !== (artist.country_code ?? "") || birthDate !== (artist.birth_date ?? "") || deathDate !== (artist.death_date ?? "") || formedYear !== (artist.formed_year?.toString() ?? "") || dissolvedYear !== (artist.dissolved_year?.toString() ?? ""));
  const cancel = () => { if (!dirty || window.confirm("Discard unsaved artist changes?")) onCancel(); };
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); const parseYear = (value: string) => value ? Number(value) : null; if (!name.trim()) { setError("Artist name is required."); return; } if (countryCode && !/^[a-z]{2}$/i.test(countryCode.trim())) { setError("Use a two-letter ISO country code, such as ES or US."); return; } if ((formedYear && (!Number.isInteger(parseYear(formedYear)) || parseYear(formedYear)! < 1 || parseYear(formedYear)! > 9999)) || (dissolvedYear && (!Number.isInteger(parseYear(dissolvedYear)) || parseYear(dissolvedYear)! < 1 || parseYear(dissolvedYear)! > 9999))) { setError("Enter valid four-digit years."); return; }
    setSaving(true); try { await updateArtist(artistId, { name: name.trim(), artist_type: type, country_code: countryCode.trim().toUpperCase() || null, birth_date: type === "person" ? birthDate || null : null, death_date: type === "person" ? deathDate || null : null, formed_year: type === "group" ? parseYear(formedYear) : null, dissolved_year: type === "group" ? parseYear(dissolvedYear) : null }); onSaved(); } catch (cause) { setError((cause as Error).message); } finally { setSaving(false); }
  }
  if (!artist) return <main className="page narrow"><button className="back" onClick={onCancel}>← Artist</button><p>{error || "Loading artist…"}</p></main>;
  return <main className="page narrow edit-artist-page"><button className="back" onClick={cancel}>← Artist</button><p className="eyebrow">Artist metadata</p><h1>Edit artist</h1><form onSubmit={submit} noValidate><section className="artist-edit-section"><h2>Artist details</h2><label>Name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Type<select value={type} onChange={(event) => setType(event.target.value as ArtistType)}><option value="unknown">Unknown</option><option value="person">Person</option><option value="group">Group</option></select></label><label>Country / origin <small>ISO code, e.g. ES or US</small><input value={countryCode} maxLength={2} onChange={(event) => setCountryCode(event.target.value.toUpperCase())} placeholder="ES" /></label>{type === "person" && <div className="metadata"><label>Birth date<input type="date" value={birthDate} onChange={(event) => setBirthDate(event.target.value)} /></label><label>Death date <small>Optional</small><input type="date" value={deathDate} onChange={(event) => setDeathDate(event.target.value)} /></label></div>}{type === "group" && <div className="metadata"><label>Formed<input type="number" min="1" max="9999" value={formedYear} onChange={(event) => setFormedYear(event.target.value)} /></label><label>Dissolved <small>Optional</small><input type="number" min="1" max="9999" value={dissolvedYear} onChange={(event) => setDissolvedYear(event.target.value)} /></label></div>}</section><section className="artist-edit-section"><h2>Artist image</h2><div className="artist-edit-image"><ArtistImage artist={artist} className="artist-hero-image" /><ArtistImageControls artist={artist} onUpdated={(updated) => setArtist((current) => current ? { ...current, image_url: updated.image_url } : current)} /></div></section>{error && <p className="notice error" role="alert">{error}</p>}<div className="edit-album-actions"><button type="button" className="text-button" onClick={cancel}>Cancel</button><button type="submit" disabled={saving}>{saving ? "Saving…" : "Save changes"}</button></div></form></main>;
}
