import { FormEvent, useState } from "react";
import { createAlbum } from "../../api/albums";
import type { AlbumCreate, ReleaseType } from "../../api/types";

const releaseTypes: ReleaseType[] = ["album", "ep", "mixtape", "compilation", "live", "reissue"];
type DraftTrack = { title: string; discNumber: number };

export function CreateAlbumPage({ onCancel, onCreated }: { onCancel: () => void; onCreated: (id: number) => void }) {
  const [title, setTitle] = useState(""); const [artists, setArtists] = useState([""]); const [year, setYear] = useState(""); const [releaseType, setReleaseType] = useState<ReleaseType>("album"); const [discCount, setDiscCount] = useState(1);
  const [tracks, setTracks] = useState<DraftTrack[]>([{ title: "", discNumber: 1 }]); const [bulk, setBulk] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const updateTrack = (index: number, change: Partial<DraftTrack>) => setTracks((current) => current.map((track, itemIndex) => itemIndex === index ? { ...track, ...change } : track));
  const changeDiscCount = (value: string) => { const count = Number(value); if (!Number.isInteger(count) || count < 1 || count > 99) return; setDiscCount(count); setTracks((current) => current.map((track) => ({ ...track, discNumber: Math.min(track.discNumber, count) }))); };
  const addPastedTracks = () => { const pasted = bulk.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); if (pasted.length) { setTracks((current) => [...current.filter((track) => track.title.trim()), ...pasted.map((title) => ({ title, discNumber: 1 }))]); setBulk(""); } };
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); const cleanTracks = tracks.map((track) => ({ ...track, title: track.title.trim() })).filter((track) => track.title); const cleanArtists = artists.map((artist) => artist.trim()).filter(Boolean); if (!title.trim() || !cleanArtists.length || !cleanTracks.length) { setError("Title, at least one artist, and one track are required."); return; }
    const parsedYear = year ? Number(year) : null; if (parsedYear !== null && (!Number.isInteger(parsedYear) || parsedYear < 1000 || parsedYear > 3000)) { setError("Enter a valid year."); return; }
    const positions = new Map<number, number>(); const payload: AlbumCreate = { title: title.trim(), artists: cleanArtists.map((name) => ({ name })), year: parsedYear, release_type: releaseType, disc_count: discCount, tracks: cleanTracks.map((track) => { const position = (positions.get(track.discNumber) ?? 0) + 1; positions.set(track.discNumber, position); return { title: track.title, disc_number: track.discNumber, position }; }) };
    setSaving(true); try { const album = await createAlbum(payload); onCreated(album.id); } catch (cause) { setError((cause as Error).message); } finally { setSaving(false); }
  }
  return <main className="page narrow"><button className="back" onClick={onCancel}>← Albums</button><p className="eyebrow">New entry</p><h1>Add an album</h1><form onSubmit={submit} noValidate>
    <div className="metadata"><label>Title<input value={title} onChange={(event) => setTitle(event.target.value)} required /></label><div><p className="eyebrow">Artists</p>{artists.map((artist, index) => <div className="artist-input" key={index}><input aria-label={`Artist ${index + 1}`} value={artist} onChange={(event) => setArtists((current) => current.map((value, itemIndex) => itemIndex === index ? event.target.value : value))} />{artists.length > 1 && <button type="button" className="icon-button" onClick={() => setArtists((current) => current.filter((_, itemIndex) => itemIndex !== index))}>×</button>}</div>)}<button type="button" className="text-button" onClick={() => setArtists((current) => [...current, ""])}>+ Add artist</button></div><label>Year<input type="number" min="1000" max="3000" value={year} onChange={(event) => setYear(event.target.value)} /></label><label>Release type<select value={releaseType} onChange={(event) => setReleaseType(event.target.value as ReleaseType)}>{releaseTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label>Number of discs<input type="number" min="1" max="99" value={discCount} onChange={(event) => changeDiscCount(event.target.value)} /></label></div>
    <section className="form-section"><div className="section-heading"><h2>Tracklist</h2><button type="button" className="text-button" onClick={() => setTracks((current) => [...current, { title: "", discNumber: 1 }])}>+ Add track</button></div>{tracks.map((track, index) => <div className="track-title" key={index}><span>{String((tracks.slice(0, index).filter((item) => item.discNumber === track.discNumber).length) + 1).padStart(2, "0")}</span><input aria-label={`Track ${index + 1} title`} value={track.title} onChange={(event) => updateTrack(index, { title: event.target.value })} />{discCount > 1 && <select aria-label={`Track ${index + 1} disc`} value={track.discNumber} onChange={(event) => updateTrack(index, { discNumber: Number(event.target.value) })}>{Array.from({ length: discCount }, (_, discIndex) => <option value={discIndex + 1} key={discIndex}>Disc {discIndex + 1}</option>)}</select>}{tracks.length > 1 && <button type="button" aria-label={`Remove track ${index + 1}`} className="icon-button" onClick={() => setTracks((current) => current.filter((_, itemIndex) => itemIndex !== index))}>×</button>}</div>)}
    <label className="bulk">Paste a tracklist (one title per line)<textarea value={bulk} onChange={(event) => setBulk(event.target.value)} rows={4} /><button type="button" className="text-button" onClick={addPastedTracks}>Add pasted tracks to Disc 1</button></label></section>
    {error && <p className="notice error" role="alert">{error}</p>}<button type="submit" disabled={saving}>{saving ? "Creating…" : "Create album"}</button>
  </form></main>;
}
