import { FormEvent, useState } from "react";
import { createAlbum } from "../../api/albums";
import type { AlbumCreate, ReleaseType } from "../../api/types";

const releaseTypes: ReleaseType[] = ["album", "ep", "mixtape", "compilation"];
export function CreateAlbumPage({ onCancel, onCreated }: { onCancel: () => void; onCreated: (id: number) => void }) {
  const [title, setTitle] = useState(""); const [artists, setArtists] = useState([""]); const [year, setYear] = useState(""); const [releaseType, setReleaseType] = useState<ReleaseType>("album");
  const [tracks, setTracks] = useState<string[]>([""]); const [bulk, setBulk] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const updateTrack = (index: number, value: string) => setTracks((current) => current.map((track, i) => i === index ? value : track));
  const addPastedTracks = () => { const pasted = bulk.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); if (pasted.length) { setTracks((current) => [...current.filter(Boolean), ...pasted]); setBulk(""); } };
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); const cleanTracks = tracks.map((track) => track.trim()).filter(Boolean); const cleanArtists = artists.map((artist) => artist.trim()).filter(Boolean); if (!title.trim() || !cleanArtists.length || !cleanTracks.length) { setError("Title, at least one artist, and at least one track are required."); return; }
    const parsedYear = year ? Number(year) : null; if (parsedYear !== null && (!Number.isInteger(parsedYear) || parsedYear < 1000 || parsedYear > 3000)) { setError("Enter a valid year."); return; }
    const payload: AlbumCreate = { title: title.trim(), artists: cleanArtists.map((name) => ({ name })), year: parsedYear, release_type: releaseType, tracks: cleanTracks.map((track, index) => ({ title: track, position: index + 1 })) };
    setSaving(true); try { const album = await createAlbum(payload); onCreated(album.id); } catch (e) { setError((e as Error).message); } finally { setSaving(false); }
  }
  return <main className="page narrow"><button className="back" onClick={onCancel}>← Albums</button><p className="eyebrow">New entry</p><h1>Add an album</h1><form onSubmit={submit} noValidate>
    <div className="metadata"><label>Title<input value={title} onChange={(e) => setTitle(e.target.value)} required /></label><div><p className="eyebrow">Artists</p>{artists.map((artist, index) => <div className="artist-input" key={index}><input aria-label={`Artist ${index + 1}`} value={artist} onChange={(e) => setArtists((current) => current.map((value, i) => i === index ? e.target.value : value))} />{artists.length > 1 && <button type="button" className="icon-button" onClick={() => setArtists((current) => current.filter((_, i) => i !== index))}>×</button>}</div>)}<button type="button" className="text-button" onClick={() => setArtists((current) => [...current, ""])}>+ Add artist</button></div><label>Year<input type="number" min="1000" max="3000" value={year} onChange={(e) => setYear(e.target.value)} /></label><label>Release type<select value={releaseType} onChange={(e) => setReleaseType(e.target.value as ReleaseType)}>{releaseTypes.map((type) => <option key={type}>{type}</option>)}</select></label></div>
    <section className="form-section"><div className="section-heading"><h2>Tracklist</h2><button type="button" className="text-button" onClick={() => setTracks((current) => [...current, ""])}>+ Add track</button></div>{tracks.map((track, index) => <div className="track-title" key={index}><span>{String(index + 1).padStart(2, "0")}</span><input aria-label={`Track ${index + 1} title`} value={track} onChange={(e) => updateTrack(index, e.target.value)} />{tracks.length > 1 && <button type="button" aria-label={`Remove track ${index + 1}`} className="icon-button" onClick={() => setTracks((current) => current.filter((_, i) => i !== index))}>×</button>}</div>)}
    <label className="bulk">Paste a tracklist (one title per line)<textarea value={bulk} onChange={(e) => setBulk(e.target.value)} rows={4} /><button type="button" className="text-button" onClick={addPastedTracks}>Add pasted tracks</button></label></section>
    {error && <p className="notice error" role="alert">{error}</p>}<button type="submit" disabled={saving}>{saving ? "Creating…" : "Create album"}</button>
  </form></main>;
}
