import { type FormEvent, useEffect, useState } from "react";
import { getAlbum, updateAlbum, updateTrackArtists } from "../../api/albums";
import type { Album, AlbumUpdate, Artist, ReleaseType, TrackUpdate } from "../../api/types";
import { AlbumCover } from "./AlbumCover";
import { CoverControls } from "./CoverControls";
import { addTrackToDisc, canUseDiscCount, moveTrackWithinDisc, parseTracklistText } from "./tracklistEditor";
import { ArtistSearchPicker } from "../artists/ArtistSearchPicker";

const releaseTypes: ReleaseType[] = ["album", "ep", "mixtape", "compilation", "live", "reissue"];
type Credits = Record<number, { primary: Artist[]; featured: Artist[] }>;

export function EditAlbumPage({ albumId, onCancel, onSaved }: { albumId: number; onCancel: () => void; onSaved: () => void }) {
  const [album, setAlbum] = useState<Album | null>(null); const [title, setTitle] = useState(""); const [artists, setArtists] = useState<string[]>([]); const [year, setYear] = useState(""); const [releaseType, setReleaseType] = useState<ReleaseType>("album"); const [discCount, setDiscCount] = useState(1);
  const [tracks, setTracks] = useState<TrackUpdate[]>([]); const [tracklistText, setTracklistText] = useState(""); const [credits, setCredits] = useState<Credits>({}); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { getAlbum(albumId).then((loaded) => { setAlbum(loaded); setTitle(loaded.title); setArtists(loaded.artists.map((artist) => artist.name)); setYear(loaded.year?.toString() ?? ""); setReleaseType(loaded.release_type); setDiscCount(loaded.disc_count); setTracks(loaded.tracks.map((track) => ({ id: track.id, disc_number: track.disc_number, title: track.title }))); setCredits(Object.fromEntries(loaded.tracks.map((track) => [track.id, { primary: track.uses_album_artists ? [] : track.primary_artists, featured: track.featured_artists }]))); }).catch((cause: Error) => setError(cause.message)).finally(() => setLoading(false)); }, [albumId]);
  const setTrackCredit = (trackId: number, kind: "primary" | "featured", selected: Artist[]) => setCredits((current) => ({ ...current, [trackId]: { ...current[trackId], [kind]: selected } }));
  const moveTrack = (index: number, direction: -1 | 1) => setTracks((current) => moveTrackWithinDisc(current, index, direction));
  const changeDiscCount = (value: string) => { const next = Number(value); if (!Number.isInteger(next) || next < 1 || next > 99) return; if (!canUseDiscCount(tracks, next)) { setError(`Cannot reduce disc count while Disc ${next + 1} or later contains tracks. Move or delete those tracks first.`); return; } setError(null); setDiscCount(next); };
  const addPastedTracks = () => setTracks(parseTracklistText(tracklistText));
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); const parsedYear = year ? Number(year) : null; const cleanArtists = artists.map((artist) => artist.trim()).filter(Boolean); if (!title.trim() || !cleanArtists.length) { setError("Title and at least one artist are required."); return; } if (parsedYear !== null && (!Number.isInteger(parsedYear) || parsedYear < 1000 || parsedYear > 3000)) { setError("Enter a valid year."); return; } if (!tracks.length || tracks.some((track) => !track.title.trim())) { setError("Add at least one track with a title."); return; }
    const orderedTracks = Array.from({ length: discCount }, (_, discIndex) => tracks.filter((track) => track.disc_number === discIndex + 1)).flat(); const payload: AlbumUpdate = { title: title.trim(), artists: cleanArtists.map((name) => ({ name })), year: parsedYear, release_type: releaseType, disc_count: discCount, tracks: orderedTracks.map((track) => ({ ...track, title: track.title.trim() })) };
    setSaving(true); try { const saved = await updateAlbum(albumId, payload); const savedIds = new Set(saved.tracks.map((track) => track.id)); await Promise.all(Object.entries(credits).filter(([trackId]) => savedIds.has(Number(trackId))).map(([trackId, value]) => updateTrackArtists(Number(trackId), { primary_artist_ids: value.primary.map((artist) => artist.id), featured_artist_ids: value.featured.map((artist) => artist.id) }))); onSaved(); } catch (cause) { setError((cause as Error).message); } finally { setSaving(false); }
  }
  if (loading) return <main className="page"><p>Loading album…</p></main>; if (!album) return <main className="page"><button className="back" onClick={onCancel}>← Album</button><p className="notice error">{error || "Album not found."}</p></main>;
  return <main className="page narrow edit-album-page"><button className="back" onClick={onCancel}>← Album</button><p className="eyebrow">Album metadata</p><h1>Edit album</h1><form onSubmit={submit} noValidate><div className="edit-album-cover"><AlbumCover album={album} className="edit-cover" /><div><h2>Cover art</h2><CoverControls album={album} onUpdated={setAlbum} /></div></div>
    <div className="metadata"><label>Title<input value={title} onChange={(event) => setTitle(event.target.value)} required /></label><div><p className="eyebrow">Artists</p>{artists.map((artist, index) => <div className="artist-input" key={index}><input value={artist} onChange={(event) => setArtists((current) => current.map((value, itemIndex) => itemIndex === index ? event.target.value : value))} />{artists.length > 1 && <button type="button" className="icon-button" onClick={() => setArtists((current) => current.filter((_, itemIndex) => itemIndex !== index))}>×</button>}</div>)}<button type="button" className="text-button" onClick={() => setArtists((current) => [...current, ""])}>+ Add artist</button></div><label>Year<input type="number" min="1000" max="3000" value={year} onChange={(event) => setYear(event.target.value)} /></label><label>Release type<select value={releaseType} onChange={(event) => setReleaseType(event.target.value as ReleaseType)}>{releaseTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label>Number of discs<input type="number" min="1" max="99" value={discCount} onChange={(event) => changeDiscCount(event.target.value)} /></label></div>
    <section className="form-section"><h2>Tracklist</h2>{!tracks.length ? <><p>No tracks added yet. Add the album's tracklist to enable native ratings.</p><label>Paste tracklist<textarea rows={7} value={tracklistText} onChange={(event) => setTracklistText(event.target.value)} placeholder="One track per line" /></label><button type="button" className="text-button" onClick={addPastedTracks}>Use pasted tracks</button></> : Array.from({ length: discCount }, (_, discIndex) => { const disc = discIndex + 1; const discTracks = tracks.flatMap((track, index) => track.disc_number === disc ? [{ track, index }] : []); return <section className="track-disc-editor" key={disc}>{discCount > 1 && <h3>Disc {disc}</h3>}{discTracks.map(({ track, index }, localIndex) => <div className="tracklist-editor" key={track.id ?? `new-${disc}-${index}`}><span>{String(localIndex + 1).padStart(2, "0")}</span><input value={track.title} onChange={(event) => setTracks((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item))} aria-label={`Disc ${disc} track ${localIndex + 1} title`} />{discCount > 1 && <select aria-label={`Move ${track.title || "track"} to disc`} value={track.disc_number} onChange={(event) => setTracks((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, disc_number: Number(event.target.value) } : item))}>{Array.from({ length: discCount }, (_, targetIndex) => <option key={targetIndex} value={targetIndex + 1}>Disc {targetIndex + 1}</option>)}</select>}<button type="button" className="text-button track-move" onClick={() => moveTrack(index, -1)} disabled={localIndex === 0}>↑</button><button type="button" className="text-button track-move" onClick={() => moveTrack(index, 1)} disabled={localIndex === discTracks.length - 1}>↓</button><button type="button" className="text-button" onClick={() => setTracks((current) => current.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></div>)}<button type="button" className="text-button" onClick={() => setTracks((current) => addTrackToDisc(current, disc))}>+ Add track</button></section>; })}</section>
    {tracks.some((track) => track.id !== undefined) && <section className="form-section"><h2>Track credits</h2><p>Search artists to assign explicit credits.</p>{album.tracks.filter((track) => tracks.some((draft) => draft.id === track.id)).map((track) => <div className="track-credit-editor" key={track.id}><strong>{track.title}</strong><ArtistSearchPicker label="Primary artists" selected={credits[track.id]?.primary ?? []} onChange={(selected) => setTrackCredit(track.id, "primary", selected)} helper="Leave empty to inherit album artists." /><ArtistSearchPicker label="Featured artists" selected={credits[track.id]?.featured ?? []} onChange={(selected) => setTrackCredit(track.id, "featured", selected)} /></div>)}</section>}{error && <p className="notice error" role="alert">{error}</p>}<div className="edit-album-actions"><button type="button" className="text-button" onClick={onCancel}>Cancel</button><button type="submit" disabled={saving}>{saving ? "Saving…" : "Save changes"}</button></div>
  </form></main>;
}
