import { useState } from "react";
import { getMusicBrainzRelease, searchMusicBrainzReleases } from "../../api/musicbrainz";
import type { MusicBrainzReleasePreview, MusicBrainzSearchResult } from "../../api/types";

export function MusicBrainzAlbumEnrichment({ title, artists, onUseTracklist, onImportCover }: { title: string; artists: string[]; onUseTracklist: (preview: MusicBrainzReleasePreview) => void; onImportCover: (url: string) => Promise<void> }) {
  const [query, setQuery] = useState(title); const [artist, setArtist] = useState(artists.join(", ")); const [results, setResults] = useState<MusicBrainzSearchResult[]>([]); const [preview, setPreview] = useState<MusicBrainzReleasePreview | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function search() { if (!query.trim()) { setError("Enter an album title to search."); return; } setBusy(true); setError(null); try { setPreview(null); setResults(await searchMusicBrainzReleases(query.trim(), artist)); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  async function select(result: MusicBrainzSearchResult) { setBusy(true); setError(null); try { setPreview(await getMusicBrainzRelease(result.musicbrainz_release_id)); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  async function importCover() { if (!preview?.cover_url) return; setBusy(true); setError(null); try { await onImportCover(preview.cover_url); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  return <section className="form-section musicbrainz-enrichment"><h2>MusicBrainz</h2><p className="musicbrainz-helper">Find an existing release to bring in its tracklist or locally store its cover art.</p><div className="metadata musicbrainz-search"><label>Album title<input value={query} onChange={(event) => setQuery(event.target.value)} /></label><label>Artist (optional)<input value={artist} onChange={(event) => setArtist(event.target.value)} /></label></div><div className="musicbrainz-actions"><button type="button" onClick={search} disabled={busy}>{busy ? "Searching…" : "Search MusicBrainz"}</button></div>{results.length > 0 && !preview && <ol className="album-list musicbrainz-results">{results.map((result) => <li key={result.musicbrainz_release_id}><button type="button" className="album-link" onClick={() => select(result)}><strong>{result.title}</strong><span>{result.artists.join(" & ")} · {result.date ?? "Date unknown"} · {result.disc_count} disc{result.disc_count === 1 ? "" : "s"} · {result.track_count} tracks</span></button></li>)}</ol>}{preview && <div className="musicbrainz-preview"><p><strong>{preview.title}</strong> · {preview.artists.join(" & ")} · {preview.disc_count} disc{preview.disc_count === 1 ? "" : "s"} · {preview.tracks.length} tracks</p><div className="library-actions"><button type="button" onClick={() => onUseTracklist(preview)} disabled={busy}>Use MusicBrainz tracklist</button>{preview.cover_url ? <button type="button" className="text-button" onClick={importCover} disabled={busy}>{busy ? "Importing cover…" : "Import MusicBrainz cover"}</button> : <span>No cover available for this release.</span>}<button type="button" className="text-button" onClick={() => setPreview(null)} disabled={busy}>Choose another release</button></div></div>}{error && <p className="notice error musicbrainz-feedback" role="alert">{error}</p>}</section>;
}
