import { useState } from "react";
import { getMusicBrainzRelease, importMusicBrainzRelease, searchMusicBrainzReleases } from "../../api/musicbrainz";
import type { MusicBrainzReleasePreview, MusicBrainzSearchResult } from "../../api/types";
import { musicBrainzImportPayload } from "./musicbrainz";

export function MusicBrainzImportPanel({ onImported }: { onImported: (id: number) => void }) {
  const [query, setQuery] = useState(""); const [artist, setArtist] = useState(""); const [results, setResults] = useState<MusicBrainzSearchResult[]>([]); const [preview, setPreview] = useState<MusicBrainzReleasePreview | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const search = async () => { if (!query.trim()) return; setBusy(true); setError(null); try { setResults(await searchMusicBrainzReleases(query.trim(), artist)); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } };
  const select = async (release: MusicBrainzSearchResult) => { setBusy(true); setError(null); try { setPreview(await getMusicBrainzRelease(release.musicbrainz_release_id)); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } };
  const update = (change: Partial<MusicBrainzReleasePreview>) => setPreview((current) => current ? { ...current, ...change } : current);
  const submit = async () => { if (!preview) return; setBusy(true); setError(null); try { const album = await importMusicBrainzRelease(musicBrainzImportPayload(preview)); onImported(album.id); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } };
  return <section className="form-section"><h2>Import from MusicBrainz</h2>{!preview ? <><div className="metadata"><label>Album title<input value={query} onChange={(event) => setQuery(event.target.value)} /></label><label>Artist (optional)<input value={artist} onChange={(event) => setArtist(event.target.value)} /></label></div><button type="button" onClick={search} disabled={busy}>{busy ? "Searching…" : "Search MusicBrainz"}</button>{results.length > 0 && <ol className="album-list">{results.map((result) => <li key={result.musicbrainz_release_id}><button type="button" className="album-link" onClick={() => select(result)}><strong>{result.title}</strong><span>{result.artists.join(" & ")} · {result.date ?? "Date unknown"}{result.country ? ` · ${result.country}` : ""} · {result.disc_count} disc{result.disc_count === 1 ? "" : "s"} · {result.track_count} tracks{result.disambiguation ? ` · ${result.disambiguation}` : ""}</span></button></li>)}</ol>}</> : <><div className="metadata"><label>Title<input value={preview.title} onChange={(event) => update({ title: event.target.value })} /></label><label>Artists<input value={preview.artists.join(", ")} onChange={(event) => update({ artists: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} /></label><label>Year<input type="number" value={preview.year ?? ""} onChange={(event) => update({ year: event.target.value ? Number(event.target.value) : null })} /></label><label>Release type<select value={preview.release_type} onChange={(event) => update({ release_type: event.target.value as MusicBrainzReleasePreview["release_type"] })}><option value="album">album</option><option value="ep">ep</option><option value="mixtape">mixtape</option><option value="compilation">compilation</option><option value="live">live</option><option value="reissue">reissue</option></select></label></div><section className="form-section"><h3>Tracklist</h3>{Array.from({ length: preview.disc_count }, (_, index) => index + 1).map((disc) => <section className="track-disc-editor" key={disc}>{preview.disc_count > 1 && <h3>Disc {disc}</h3>}{preview.tracks.filter((track) => track.disc_number === disc).map((track, index) => <div className="track-title" key={`${disc}-${track.position}`}><span>{String(index + 1).padStart(2, "0")}</span><input value={track.title} onChange={(event) => update({ tracks: preview.tracks.map((item) => item === track ? { ...item, title: event.target.value } : item) })} /></div>)}</section>)}</section><button type="button" className="text-button" onClick={() => setPreview(null)}>Back to results</button><button type="button" onClick={submit} disabled={busy}>{busy ? "Importing…" : "Import album"}</button></>}{error && <p className="notice error" role="alert">{error}</p>}</section>;
}
